/**
 * gen-config.js
 * Reads GOOGLE_API_KEY from .env (or existing env) and writes dashboard-config.js
 * so the browser dashboard never asks for the API key.
 * Called automatically by launch.json before starting the dev server.
 */
const fs = require('fs');
const path = require('path');

function parseDotEnv(filePath) {
  try {
    const lines = fs.readFileSync(filePath, 'utf8').split('\n');
    const env = {};
    for (const line of lines) {
      const m = line.match(/^\s*([^#=][^=]*?)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      let val = m[2].trim();
      // Strip surrounding quotes
      if ((val.startsWith('"') && val.endsWith('"')) ||
          (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      env[m[1].trim()] = val;
    }
    return env;
  } catch {
    return {};
  }
}

const dotEnv = parseDotEnv(path.join(__dirname, '.env'));
const apiKey = dotEnv.GOOGLE_API_KEY || process.env.GOOGLE_API_KEY || '';

const content = `/* Auto-generated by gen-config.js — do not commit (in .gitignore) */
window.GOOGLE_API_KEY = ${JSON.stringify(apiKey)};
`;

fs.writeFileSync(path.join(__dirname, 'dashboard-config.js'), content, 'utf8');

if (apiKey) {
  console.log('✓ dashboard-config.js written — API key loaded from .env');
} else {
  console.log('⚠ dashboard-config.js written — no GOOGLE_API_KEY found in .env (key input will show in dashboard)');
}
