/**
 * gen-config.js
 * Reads keys from .env and writes dashboard-config.js
 * Also scans exports/ folder and writes exports/cities.json
 * Called automatically by launch.json before starting the dev server.
 */
const fs   = require('fs');
const path = require('path');

function parseDotEnv(filePath) {
  try {
    const lines = fs.readFileSync(filePath, 'utf8').split('\n');
    const env   = {};
    for (const line of lines) {
      const m = line.match(/^\s*([^#=][^=]*?)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      let val = m[2].trim();
      if ((val.startsWith('"') && val.endsWith('"')) ||
          (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      env[m[1].trim()] = val;
    }
    return env;
  } catch { return {}; }
}

const dotEnv  = parseDotEnv(path.join(__dirname, '.env'));
const apiKey  = dotEnv.GOOGLE_API_KEY || process.env.GOOGLE_API_KEY || '';
const ghToken = dotEnv.GITHUB_TOKEN   || process.env.GITHUB_TOKEN   || '';
const ghRepo  = dotEnv.GITHUB_REPO    || process.env.GITHUB_REPO    || 'vashish39/business-webpages';

// ── Write dashboard-config.js ─────────────────────────────────────────────────
const configContent = `/* Auto-generated by gen-config.js — do not commit (in .gitignore) */
window.GOOGLE_API_KEY = ${JSON.stringify(apiKey)};
window.GITHUB_TOKEN   = ${JSON.stringify(ghToken)};
window.GITHUB_REPO    = ${JSON.stringify(ghRepo)};
`;

fs.writeFileSync(path.join(__dirname, 'dashboard-config.js'), configContent, 'utf8');

if (apiKey) {
  console.log('✓ dashboard-config.js written — Google API key loaded from .env');
} else {
  console.log('⚠ dashboard-config.js written — no GOOGLE_API_KEY found (key entry will show in dashboard)');
}
if (ghToken) {
  console.log('✓ GitHub token loaded from .env');
} else {
  console.log('⚠ No GITHUB_TOKEN in .env — add it to enable one-click GitHub commits from dashboard');
}

// ── Scan exports/cities/ for city CSVs + exports/enriched/ for per-place CSVs ─
const citiesDir  = path.join(__dirname, 'exports', 'cities');
const enrichDir  = path.join(__dirname, 'exports', 'enriched');
const exportsDir = path.join(__dirname, 'exports');
const cities     = [];
const seen       = new Set();

if (fs.existsSync(citiesDir)) {
  for (const f of fs.readdirSync(citiesDir).sort()) {
    if (!f.toLowerCase().endsWith('.csv')) continue;
    // Accept both "Austin.csv" and "places_Austin.csv"
    const key     = f.replace(/\.csv$/i, '').replace(/^places_/i, '');
    const display = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    if (seen.has(key.toLowerCase())) continue;
    seen.add(key.toLowerCase());

    // Find enriched CSVs for this city
    const enrichedPaths = [];
    if (fs.existsSync(enrichDir)) {
      for (const ef of fs.readdirSync(enrichDir).sort()) {
        const prefix = key.toLowerCase() + '_';
        if (ef.toLowerCase().startsWith(prefix) && ef.toLowerCase().endsWith('.csv')) {
          enrichedPaths.push(`exports/enriched/${ef}`);
        }
      }
    }

    cities.push({ name: display, key, csvPath: `exports/cities/${f}`, enrichedPaths });
  }
}

if (!fs.existsSync(exportsDir)) fs.mkdirSync(exportsDir, { recursive: true });

fs.writeFileSync(
  path.join(exportsDir, 'cities.json'),
  JSON.stringify(cities, null, 2),
  'utf8'
);

const cityNames = cities.map(c => c.name).join(', ') || '(none)';
console.log(`✓ exports/cities.json written — ${cities.length} cit${cities.length === 1 ? 'y' : 'ies'}: ${cityNames}`);
